### ISSUE TITLE
Feature: Show recommendations appears after successful survey

### ISSUE THREAD

**Issue by cavazd** [info442-spr22/h-team#54] opened 2022-05-18 16:22 UTC
* Description: Currently the Show Recommendations button and header for "Recommend for you" is always present. Instead of this, it becomes visible after finishing a survey.
* Explanation: It's a bit confusing having the button there early. I tried to click on it and nothing happened (a bug someone else has mentioned I think) but then I assumed I had to finish the survey first. Finishing the survey first and then getting recommendations makes the most sense in my opinion.

**Comment by mariamk-2740** [comment] 2022-05-23 18:27
We see how this could help our site, but may not be able to address it in the time we have during this sprint

**Comment by mariamk-2740** [comment] 2022-05-23 18:28
We can address this enhancement during the sprint.

**Comment by mariamk-2740** [comment] 2022-05-23 18:53
We realized that this enhancement is a duplicate of [issue](https://github.com/info442-spr22/h-team/issues/46)

**Closed by mariamk-2740** 2022-05-23 18:53 UTC
Labels: duplicate, enhancement
